### ISSUE TITLE
Работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [myroslav-bakuta/grid-template-init-project#1]
картинка повторяется
![image](https://user-images.githubusercontent.com/8464662/77103161-a5b8b780-6a22-11ea-823c-48dc394e4cbc.png)

1)
цвет плейсхолдера не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/77103203-b701c400-6a22-11ea-9fe0-3a2f7bcde17b.png)

**Comment by myroslav-bakuta** [comment]
Виправлено

**Comment by Alecto** [comment]
отлично

сб, 21 бер. 2020 о 20:22 Myroslav <notifications@github.com> пише:
